version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  builder: html
  configuration: doc/conf.py

python:
   install:
     - requirements: doc/requirements.txt
     - requirements: requirements.txt
     - method: pip
       path: .
