name: Test minimal

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install
        run: python -m pip install pytest pytest-cov psutil==5.4 .

      - name: pytest
        run: py.test --verbose --cov=pshell --cov-report=xml

      - name: codecov.io
        uses: codecov/codecov-action@v3
