name: Test latest

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        include:
          - os: macos
            python-version: "3.8"
          - os: macos
            python-version: "3.12"
          - os: windows
            python-version: "3.8"
          - os: windows
            python-version: "3.12"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: python -m pip install pytest pytest-cov .

      - name: pytest
        run: py.test --verbose --cov=pshell --cov-report=xml

      - name: codecov.io
        uses: codecov/codecov-action@v3
